// messenger-react/src/components/messenger/groups.js
import React from 'react';
import { render } from 'react-dom';
import Paper from 'material-ui/Paper';

class Groups extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            list: [
                {
                    id: 1,
                    img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
                    name:  'Abner Juarez',
                    message: 'Hola Mundo',
                    sentOn: '9:04 PM',
                    status: 1
                },
                {
                    id: 2,
                    img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
                    name:  'Abner Juarez 2',
                    message: 'Hola Mundo X2',
                    sentOn: '9:04 PM',
                    status: 1
                },
                {
                    id: 3,
                    img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
                    name:  'Abner Juarez 3',
                    message: 'Hola Mundo X3',
                    sentOn: '9:04 PM',
                    status: 1
                }
            ]
        }
    }

    render () {
        return (
            <div>
                <Paper zDepth={2}>
                    {this.state.list.map((element) => {
                        return <h3>This is a group {element.name}</h3>;
                    })}
                </Paper>
            </div>
        );
    }

}

export default Groups;

// messenger-app/src/app/messenger/groups/groups.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'groups',
  templateUrl: './groups.component.html'
})
export class GroupsComponent implements OnInit {

  constructor() { }

  ngOnInit() {
    this.group = [
      {
        img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
        name:  'Super Group',
        message: 'Hola Mundo',
        sentOn: '9:04 PM',
        status: 1
      },
      {
        img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
        name:  'Super Group 2',
        message: 'Hola Mundo X2',
        sentOn: '9:04 PM',
        status: 1
      },
      {
        img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
        name:  'Super Group 3',
        message: 'Hola Mundo X3',
        sentOn: '9:04 PM',
        status: 1
      }
    ]
  }

}

<div class="pl-4 pr-4 pt-2">
  <div class="row mb-3" *ngFor="let group of groups">
    <div class="col-sm-1 mr-4">
      <img class="rounded-circle user-photo"
           [src]="group.img">
    </div>

    <div class="col-sm-8 f-8">

      <div class="fw-500">{{group.name}}</div>
      <div>{{group.message}}</div>
    </div>

    <div class="col-sm-2">
      <div class="time">{{group.sentOn}}</div>
      <div>{{group.status}}</div>
    </div>
  </div>
</div>
