// messenger-app/src/app/messenger/conversations/conversations.component.ts
import { Component, OnInit } from '@angular/core';
import {ConversationService} from "../shared/conversation.service";

@Component({
  selector: 'conversations',
  templateUrl: './conversations.component.html'
})
export class ConversationsComponent implements OnInit {
  conversations = [];

  constructor(private conversationService: ConversationService) { }

  ngOnInit() {
    this.conversations = [
      {
        img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
        name:  'Abner Juarez',
        message: 'Hola Mundo',
        sentOn: '9:04 PM',
        status: 1
      },
      {
        img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
        name:  'Abner Juarez 2',
        message: 'Hola Mundo X2',
        sentOn: '9:04 PM',
        status: 1
      },
      {
        img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
        name:  'Abner Juarez 3',
        message: 'Hola Mundo X3',
        sentOn: '9:04 PM',
        status: 1
      }
    ];
  }

}

<messenger-base active="conversations"></messenger-base>
<div class="pl-4 pr-4 pt-2">
  <div class="row mb-3" *ngFor="let conversation of conversations">
    <div class="col-sm-1 mr-4">
      <img class="rounded-circle user-photo"
           [src]="conversation.img">
    </div>

    <div class="col-sm-8 f-8">

      <div class="fw-500">{{conversation.name}}</div>
      <div>{{conversation.message}}</div>
    </div>

    <div class="col-sm-2">
      <div class="time">{{conversation.sentOn}}</div>
      <div>{{conversation.status}}</div>
    </div>
  </div>
</div>

// messenger-react/src/components/messenger/conversations.js
import React from 'react';
import { render } from 'react-dom';
import Paper from 'material-ui/Paper';
import ConversationCard from '../core/conversation-card';

class Conversations extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            list: [
                {
                    id: 1,
                    img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
                    name:  'Abner Juarez',
                    message: 'Hola Mundo',
                    sentOn: '9:04 PM',
                    status: 1
                },
                {
                    id: 2,
                    img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
                    name:  'Abner Juarez 2',
                    message: 'Hola Mundo X2',
                    sentOn: '9:04 PM',
                    status: 1
                },
                {
                    id: 3,
                    img: 'data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
                    name:  'Abner Juarez 3',
                    message: 'Hola Mundo X3',
                    sentOn: '9:04 PM',
                    status: 1
                }
            ]
        }
    }

    render() {
        return (
            <div>
                <Paper zDepth={2}>
                    {this.state.list.map((element) => {
                        return <ConversationCard conversation={element} key={element.id}/>;
                    })}
                </Paper>
            </div>

        );
    }
}

export default Conversations;
